# Generated by Django 4.2.2 on 2023-06-22 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=True)),
                ('path', models.CharField(max_length=100)),
                ('flag', models.BooleanField(default=True)),
                ('merge', models.BooleanField(default=False)),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.test')),
                ('train_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
