# Generated by Django 4.2.2 on 2023-06-22 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('Accuracy', models.FloatField()),
                ('MacroF1', models.FloatField()),
                ('path', models.CharField(max_length=255)),
                ('featuresNum', models.IntegerField()),
                ('labelsNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', '成功'), ('in_progress', '进行中'), ('exception', '异常')], default='in_progress', max_length=11)),
                ('crete_time', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.CharField(max_length=255)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', '成功'), ('in_progress', '进行中'), ('exception', '失败')], default='in_progress', max_length=11)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
