# Generated by Django 4.2.2 on 2023-06-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='crete_time',
            new_name='create_time',
        ),
    ]
